org: nidhoggspec
app: serverlessdelfosti
service: RetoTecnicoDelfosti-Backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getCardData:
    handler: src/controllers/getCardData.getCardData
    name: ${sls:stage}-getCardData
    events:
      - httpApi:
          path: /cardData
          method: get
  createToken:
    handler: src/controllers/token.createToken
    name: ${sls:stage}-createToken
    events:
      - httpApi:
          path: /tokens
          method: post
plugins:
  - serverless-plugin-typescript
